export const SET_LOCALE = "SET_LOCALE";
export const SET_LOGGEDINSTATUS = "SET_LOGINSTATUS";

export const SET_PROFILE = "SET_PROFILE";

export const ADD_TO_CART = "ADD_TO_CART";
export const DEC_CART_ITEM_COUNT = "DEC_CART_ITEM_COUNT";
export const INC_CART_ITEM_COUNT = "INC_CART_ITEM_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_INVENTORY = "ADD_TO_INVENTORY";
export const SELECT_INV_ITEM = "SELECT_INV_ITEM";
export const SET_INV_ITEM_COUNT = "SET_INV_ITEM_COUNT";
export const SET_INV_ITEM = "SET_INV_ITEM";
export const REMOVE_FROM_INVENTORY = "REMOVE_FROM_INVENTORY";

export const SELECT_ORDER_ITEM = "SELECT_ORDER_ITEM";

