const REGCODE = {
    NOERROR: 0,
    USERNAME_MISSING: 1,
    USERNAME_SPACES: 2,
    PASSWORD_MISSING: 3,
    CONFIRMPWD_MISSING: 4,
    PASSWORDS_DIFF: 5, 
    EMAIL_INVALID: 6,
    USERNAME_REGISTERED: 7,
    EMAIL_REGISTERED: 8
}

module.exports = REGCODE;